### ISSUE TITLE
Soundboard effects on Overlayed

### ISSUE THREAD

**Issue by Pyr33x** [overlayeddev/overlayed#184]
When someone playing a sound effect, overlayed must be showing it as an active border (it'd be blue just like the discord itself)

https://github.com/user-attachments/assets/5e5aa3ac-f882-471c-83be-771be0bfb695

**Comment by Hacksore** [comment]
I’m not sure it’s possible because I think soundboard was only added to the RPC API to allow stream deck to play them.

I believe `VOICE_CHANNEL_EFFECT_SEND` exists at the gateway level but not on the local RPC

https://github.com/discord/discord-api-docs/pull/6025#issuecomment-2237242961

If anything changes we can revisit this.
