### ISSUE TITLE
Quitting after Pinning leaves process running.

### ISSUE THREAD

**Issue by JBlyth** [overlayeddev/overlayed#206]
After pinning Overlayed and exiting the app via the Windows Task Bar (right click on task bar icon. Click Close), the Overlayed process is left running in the Task Manager although the process seems to be closed, as it disappears from the task bar. This prevents Overlayed from being restarted.

**Comment by Hacksore** [comment]
Thanks for the bug report! Ill try and repro this and report back.

**Comment by Hacksore** [comment]
@JBlyth it's weird i have a diff experience but it's still not ideal. The tray icon stays for me and as a workaround I can "Show Overlayed" as the window get lost 🙃.

Could you please share screenshots or videos of what task manager and the tray area look like to help me figure this out.

Also what version of windows are you using?

https://github.com/user-attachments/assets/3af02381-687e-40ce-8d61-ccf29ad4f4c6

**Comment by Hacksore** [comment]
So I added a fix for this in https://github.com/overlayeddev/overlayed/commit/16222efdc40fa3b4b9656b2d71ecb8bcaa89b1d3 after saw that I hide the window on close request 😂.

So for now make sure to use the workaround by "Show Overlayed" from the task tray otherwise overlayed will remain hidden.
![image](https://github.com/user-attachments/assets/aa4ea517-5764-4a99-a145-65125e510c42)

**Comment by JBlyth** [comment]
Thanks for the workaround. But I did learn something from your post:- I didn't realise there was a Tray Icon for Overlayed - but now I do! (sorry to be slow getting back to you, I've been away having a little eye surgery ;-)

**Comment by Hacksore** [comment]
Wishing you a speedy recovery @JBlyth
