### ISSUE TITLE
Vesktop Support

### ISSUE THREAD

**Issue by aqtoo** [overlayeddev/overlayed#78]
I found overlayed and found the project to be immensely useful for when I'm in voice chats, yet when I tried setting it up I had a struggle before remembering I use [Vesktop](https://github.com/Vencord/Vesktop), is it possible at all to add support for this client? As it is majorly used across Discord.

**Comment by Hacksore** [comment]
[Inquired upstream](https://github.com/Vencord/Vesktop/issues/444#issuecomment-2131315660) as I have little knowledge of the feature parity of Vesktop.

**Comment by aqtoo** [comment]
Thanks alot anyway! Hope you can get the information you need.

**Comment by Hacksore** [comment]
Based on this https://github.com/OpenAsar/arrpc/issues/18 looks like I can't support it as of now.

Going to close this now but if something changes and Vesktop/arrpc starts supporting the [full Discord RPC API](https://discord.com/developers/docs/topics/rpc) we can revisit this.

**Comment by aqtoo** [comment]
Thanks for trying!

**Comment by claymorwan** [comment]
I'm beeging for vesktop support rn, it's one of the only discord client to allow screen share with sound on wayland I need it

**Comment by Hacksore** [comment]
@claymorwan we'd need some movement on https://github.com/OpenAsar/arrpc/issues/18 😂

**Comment by claymorwan** [comment]
> @claymorwan we'd need some movement on https://github.com/OpenAsar/arrpc/issues/18 😂

I'm still praying for it

**Comment by HungryBoy02** [comment]
Fix when?

**Comment by Neyl-123** [comment]
To get Advanced RPC working, you would need to extract data from Discord's internal state so that Overlayed could access it. Every time they adjust something it could break the extraction logic. On top of that technical hurdle, Discord's [Terms of Service](https://discord.com/terms) state:

> You may not copy, modify, create derivative works based upon, distribute, sell, lease, or sublicense any of our software or services. You also may not reverse engineer or decompile our software or services, attempt to do so, or assist anyone in doing so, unless you have our written consent or applicable law permits it.

Another way of going about this problem (and side-stepping any legal problems and accounts getting banned) is to use an open source clone of Discord like [Fluxer](https://fluxer.app/) which embraces community modifications.
